version: "3.7"
services:
  victorybandungtours:
    name: victorybandungtours
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - msa-networks
    ports:
      - 8106:80
    restart: always

networks:
  msa-networks:
    driver: bridge
    name: msa-networks
    external: true
